// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPc4_ZAcTm3UqKYovilYt6u1G7Nnvj3bs',
    appId: '1:615677482655:android:a89207001de06c7f33b4aa',
    messagingSenderId: '615677482655',
    projectId: 'dailystamp-17d6c',
    storageBucket: 'dailystamp-17d6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb5rK7Bu528Gy8RnTY-zS1DMjko2UUOvo',
    appId: '1:615677482655:ios:bd9253e41cecd50533b4aa',
    messagingSenderId: '615677482655',
    projectId: 'dailystamp-17d6c',
    storageBucket: 'dailystamp-17d6c.appspot.com',
    iosBundleId: 'com.example.dayStamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb5rK7Bu528Gy8RnTY-zS1DMjko2UUOvo',
    appId: '1:615677482655:ios:bd9253e41cecd50533b4aa',
    messagingSenderId: '615677482655',
    projectId: 'dailystamp-17d6c',
    storageBucket: 'dailystamp-17d6c.appspot.com',
    iosBundleId: 'com.example.dayStamp',
  );

}